### ISSUE TITLE
VDU 22<anything invalid> in MOS causes emulator to exit

### ISSUE THREAD

**Issue by sijnstra** [astralaster/agon-light-emulator#21] opened 2023-06-17 12:32 UTC
Using the `VDU 22` command from MOS is much more harsh than the real hardware.
If you type `vdu 22, 0` it will work, but if you type `vdu 22,0` or even just `vdu 22` the emulator will exit.
I'm using the current windows build 0.03. (13-Jun)

**Comment by astralaster** [comment] 2023-06-17 23:00
I can confirm that `VDU 22` does crash the emulator. It tries to set the mode to 62 (I dont know where this value comes from) and then the emulator panics, because there are no 62 modes available. But `VDU 22,0` just works fine (only tested on linux).

**Comment by astralaster** [comment] 2023-06-19 15:44
Should be fixed in v0.4.0.

**Closed by astralaster** 2023-06-19 15:44 UTC
Labels: bug
